/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as KontaktRouteImport } from './routes/kontakt'
import { Route as UeberUnsRouteImport } from './routes/ueber-uns'
import { Route as BfsgCheckRouteImport } from './routes/bfsg-check'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WissenWasIstBfsgRouteImport } from './routes/wissen.was-ist-bfsg'
import { Route as WissenFaqRouteImport } from './routes/wissen.faq'
import { Route as WissenBinIchBetroffenRouteImport } from './routes/wissen.bin-ich-betroffen'
import { Route as LeistungenBfsgAuditRouteImport } from './routes/leistungen.bfsg-audit'
import { Route as LeistungenBetreuungRouteImport } from './routes/leistungen.betreuung'
import { Route as LeistungenBarrierefreierOnlineshopRouteImport } from './routes/leistungen.barrierefreier-onlineshop'

const KontaktRoute = KontaktRouteImport.update({
  id: '/kontakt',
  path: '/kontakt',
  getParentRoute: () => rootRouteImport,
} as any)
const UeberUnsRoute = UeberUnsRouteImport.update({
  id: '/ueber-uns',
  path: '/ueber-uns',
  getParentRoute: () => rootRouteImport,
} as any)
const BfsgCheckRoute = BfsgCheckRouteImport.update({
  id: '/bfsg-check',
  path: '/bfsg-check',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WissenWasIstBfsgRoute = WissenWasIstBfsgRouteImport.update({
  id: '/wissen/was-ist-bfsg',
  path: '/wissen/was-ist-bfsg',
  getParentRoute: () => rootRouteImport,
} as any)
const WissenFaqRoute = WissenFaqRouteImport.update({
  id: '/wissen/faq',
  path: '/wissen/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const WissenBinIchBetroffenRoute = WissenBinIchBetroffenRouteImport.update({
  id: '/wissen/bin-ich-betroffen',
  path: '/wissen/bin-ich-betroffen',
  getParentRoute: () => rootRouteImport,
} as any)
const LeistungenBfsgAuditRoute = LeistungenBfsgAuditRouteImport.update({
  id: '/leistungen/bfsg-audit',
  path: '/leistungen/bfsg-audit',
  getParentRoute: () => rootRouteImport,
} as any)
const LeistungenBetreuungRoute = LeistungenBetreuungRouteImport.update({
  id: '/leistungen/betreuung',
  path: '/leistungen/betreuung',
  getParentRoute: () => rootRouteImport,
} as any)
const LeistungenBarrierefreierOnlineshopRoute =
  LeistungenBarrierefreierOnlineshopRouteImport.update({
    id: '/leistungen/barrierefreier-onlineshop',
    path: '/leistungen/barrierefreier-onlineshop',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bfsg-check': typeof BfsgCheckRoute
  '/kontakt': typeof KontaktRoute
  '/ueber-uns': typeof UeberUnsRoute
  '/leistungen/barrierefreier-onlineshop': typeof LeistungenBarrierefreierOnlineshopRoute
  '/leistungen/betreuung': typeof LeistungenBetreuungRoute
  '/leistungen/bfsg-audit': typeof LeistungenBfsgAuditRoute
  '/wissen/bin-ich-betroffen': typeof WissenBinIchBetroffenRoute
  '/wissen/faq': typeof WissenFaqRoute
  '/wissen/was-ist-bfsg': typeof WissenWasIstBfsgRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bfsg-check': typeof BfsgCheckRoute
  '/kontakt': typeof KontaktRoute
  '/ueber-uns': typeof UeberUnsRoute
  '/leistungen/barrierefreier-onlineshop': typeof LeistungenBarrierefreierOnlineshopRoute
  '/leistungen/betreuung': typeof LeistungenBetreuungRoute
  '/leistungen/bfsg-audit': typeof LeistungenBfsgAuditRoute
  '/wissen/bin-ich-betroffen': typeof WissenBinIchBetroffenRoute
  '/wissen/faq': typeof WissenFaqRoute
  '/wissen/was-ist-bfsg': typeof WissenWasIstBfsgRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bfsg-check': typeof BfsgCheckRoute
  '/kontakt': typeof KontaktRoute
  '/ueber-uns': typeof UeberUnsRoute
  '/leistungen/barrierefreier-onlineshop': typeof LeistungenBarrierefreierOnlineshopRoute
  '/leistungen/betreuung': typeof LeistungenBetreuungRoute
  '/leistungen/bfsg-audit': typeof LeistungenBfsgAuditRoute
  '/wissen/bin-ich-betroffen': typeof WissenBinIchBetroffenRoute
  '/wissen/faq': typeof WissenFaqRoute
  '/wissen/was-ist-bfsg': typeof WissenWasIstBfsgRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bfsg-check'
    | '/kontakt'
    | '/ueber-uns'
    | '/leistungen/barrierefreier-onlineshop'
    | '/leistungen/betreuung'
    | '/leistungen/bfsg-audit'
    | '/wissen/bin-ich-betroffen'
    | '/wissen/faq'
    | '/wissen/was-ist-bfsg'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bfsg-check'
    | '/kontakt'
    | '/ueber-uns'
    | '/leistungen/barrierefreier-onlineshop'
    | '/leistungen/betreuung'
    | '/leistungen/bfsg-audit'
    | '/wissen/bin-ich-betroffen'
    | '/wissen/faq'
    | '/wissen/was-ist-bfsg'
  id:
    | '__root__'
    | '/'
    | '/bfsg-check'
    | '/kontakt'
    | '/ueber-uns'
    | '/leistungen/barrierefreier-onlineshop'
    | '/leistungen/betreuung'
    | '/leistungen/bfsg-audit'
    | '/wissen/bin-ich-betroffen'
    | '/wissen/faq'
    | '/wissen/was-ist-bfsg'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BfsgCheckRoute: typeof BfsgCheckRoute
  KontaktRoute: typeof KontaktRoute
  UeberUnsRoute: typeof UeberUnsRoute
  LeistungenBarrierefreierOnlineshopRoute: typeof LeistungenBarrierefreierOnlineshopRoute
  LeistungenBetreuungRoute: typeof LeistungenBetreuungRoute
  LeistungenBfsgAuditRoute: typeof LeistungenBfsgAuditRoute
  WissenBinIchBetroffenRoute: typeof WissenBinIchBetroffenRoute
  WissenFaqRoute: typeof WissenFaqRoute
  WissenWasIstBfsgRoute: typeof WissenWasIstBfsgRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/ueber-uns': {
      id: '/ueber-uns'
      path: '/ueber-uns'
      fullPath: '/ueber-uns'
      preLoaderRoute: typeof UeberUnsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bfsg-check': {
      id: '/bfsg-check'
      path: '/bfsg-check'
      fullPath: '/bfsg-check'
      preLoaderRoute: typeof BfsgCheckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kontakt': {
      id: '/kontakt'
      path: '/kontakt'
      fullPath: '/kontakt'
      preLoaderRoute: typeof KontaktRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wissen/was-ist-bfsg': {
      id: '/wissen/was-ist-bfsg'
      path: '/wissen/was-ist-bfsg'
      fullPath: '/wissen/was-ist-bfsg'
      preLoaderRoute: typeof WissenWasIstBfsgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wissen/faq': {
      id: '/wissen/faq'
      path: '/wissen/faq'
      fullPath: '/wissen/faq'
      preLoaderRoute: typeof WissenFaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wissen/bin-ich-betroffen': {
      id: '/wissen/bin-ich-betroffen'
      path: '/wissen/bin-ich-betroffen'
      fullPath: '/wissen/bin-ich-betroffen'
      preLoaderRoute: typeof WissenBinIchBetroffenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leistungen/bfsg-audit': {
      id: '/leistungen/bfsg-audit'
      path: '/leistungen/bfsg-audit'
      fullPath: '/leistungen/bfsg-audit'
      preLoaderRoute: typeof LeistungenBfsgAuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leistungen/betreuung': {
      id: '/leistungen/betreuung'
      path: '/leistungen/betreuung'
      fullPath: '/leistungen/betreuung'
      preLoaderRoute: typeof LeistungenBetreuungRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leistungen/barrierefreier-onlineshop': {
      id: '/leistungen/barrierefreier-onlineshop'
      path: '/leistungen/barrierefreier-onlineshop'
      fullPath: '/leistungen/barrierefreier-onlineshop'
      preLoaderRoute: typeof LeistungenBarrierefreierOnlineshopRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BfsgCheckRoute: BfsgCheckRoute,
  KontaktRoute: KontaktRoute,
  UeberUnsRoute: UeberUnsRoute,
  LeistungenBarrierefreierOnlineshopRoute:
    LeistungenBarrierefreierOnlineshopRoute,
  LeistungenBetreuungRoute: LeistungenBetreuungRoute,
  LeistungenBfsgAuditRoute: LeistungenBfsgAuditRoute,
  WissenBinIchBetroffenRoute: WissenBinIchBetroffenRoute,
  WissenFaqRoute: WissenFaqRoute,
  WissenWasIstBfsgRoute: WissenWasIstBfsgRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
